---
- name: Configure Kops Machine
  hosts: KOPS
  tasks:
    - name: Copy files
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: '0755'  # Make it executable if needed
      loop:
        - { src: 'awscli.sh', dest: '/tmp/awscli.sh' }
        - { src: 'kubectl.sh', dest: '/tmp/kubectl.sh' }
        - { src: 'kops.sh', dest: '/tmp/kops.sh' }
        - { src: 'setupK8sClusterKops.sh', dest: '/tmp/setupK8sClusterKops.sh' }
    - name: Run multiple scripts on the remote host
      shell: "{{ item }}"
      loop:
        - /tmp/awscli.sh
        - /tmp/kubectl.sh
        - /tmp/kops.sh
        - /tmp/setupK8sClusterKops.sh
