---
# this playbook will copy 3 scripts to the kops instance then run them
# helm.sh to download and install helm binaries
# prometheus.sh to install prometheus usnig helm charts
- name: Install Helm and prometheus on Kops Machine
  hosts: KOPS
  tasks:
    - name: Copy files
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: '0755'  # Make it executable if needed
      loop:
        - { src: '../bashScripts/helm.sh', dest: '/tmp/helm.sh' }
        - { src: '../bashScripts/prometheus.sh', dest: '/tmp/prometheus.sh' }
    - name: Run multiple scripts on the remote host
      shell: "{{ item }}"
      loop:
        - /tmp/helm.sh
        - /tmp/prometheus.sh
