---
- name: Cat Jenkins Password from a Jenkins Server
  hosts: Jenkins-Server
  tasks:
    - name: Cat the file
      command: cat /path/to/your/file
      register: file_content

    - name: Display the Password
      debug:
        var: file_content.stdout
