---
# this playbook will allow you to get the initial jenkins password to login for the first time
- name: Cat Jenkins Password from a Jenkins Server
  hosts: Jenkins-Server
  become: true
  tasks:
    - name: Cat the file
      command: cat /var/lib/jenkins/secrets/initialAdminPassword
      register: file_content

    - name: Display the Password
      debug:
        var: file_content.stdout
