---
- name: Configure Kops Machine
  hosts: Jenkins-Server
  tasks:
    - name: Copy files
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: '0755' 
      loop:
        - { src: '../bashScripts/awscli.sh', dest: '/tmp/awscli.sh' }
        - { src: '../bashScripts/kubectl.sh', dest: '/tmp/kubectl.sh' }
        - { src: '../bashScripts/kops.sh', dest: '/tmp/kops.sh' }
        - { src: '../bashScripts/setupK8sClusterKops.sh', dest: '/tmp/setupK8sClusterKops.sh' }
        - { src: '../bashScripts/javaForKopsAsSlave.sh', dest: '/tmp/javaForKopsAsSlave.sh' }
    - name: Run multiple scripts on the remote host
      shell: "{{ item }}"
      loop:
        - /tmp/awscli.sh
        - /tmp/kubectl.sh
        - /tmp/kops.sh
        - /tmp/setupK8sClusterKops.sh
        - /tmp/javaForKopsAsSlave.sh